//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderIntake.Infrastructure.Legado.Gerado
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarEReservarPedidoRequest", Namespace="http://legado.zeraustech.com/pedidos")]
    public partial class ValidarEReservarPedidoRequest : object
    {
        
        private System.Guid ClienteIdField;
        
        private OrderIntake.Infrastructure.Legado.Gerado.ItemPedidoLegado[] ItensField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClienteId
        {
            get
            {
                return this.ClienteIdField;
            }
            set
            {
                this.ClienteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderIntake.Infrastructure.Legado.Gerado.ItemPedidoLegado[] Itens
        {
            get
            {
                return this.ItensField;
            }
            set
            {
                this.ItensField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPedidoLegado", Namespace="http://legado.zeraustech.com/pedidos")]
    public partial class ItemPedidoLegado : object
    {
        
        private System.Guid ProdutoIdField;
        
        private int QuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProdutoId
        {
            get
            {
                return this.ProdutoIdField;
            }
            set
            {
                this.ProdutoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarEReservarPedidoResponse", Namespace="http://legado.zeraustech.com/pedidos")]
    public partial class ValidarEReservarPedidoResponse : object
    {
        
        private bool AprovadoField;
        
        private string MotivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aprovado
        {
            get
            {
                return this.AprovadoField;
            }
            set
            {
                this.AprovadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://legado.zeraustech.com/pedidos", ConfigurationName="OrderIntake.Infrastructure.Legado.Gerado.IServicoLegado")]
    public interface IServicoLegado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://legado.zeraustech.com/pedidos/IServicoLegado/ValidarEReservarPedido", ReplyAction="http://legado.zeraustech.com/pedidos/IServicoLegado/ValidarEReservarPedidoRespons" +
            "e")]
        System.Threading.Tasks.Task<OrderIntake.Infrastructure.Legado.Gerado.ValidarEReservarPedidoResponse> ValidarEReservarPedidoAsync(OrderIntake.Infrastructure.Legado.Gerado.ValidarEReservarPedidoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicoLegadoChannel : OrderIntake.Infrastructure.Legado.Gerado.IServicoLegado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicoLegadoClient : System.ServiceModel.ClientBase<OrderIntake.Infrastructure.Legado.Gerado.IServicoLegado>, OrderIntake.Infrastructure.Legado.Gerado.IServicoLegado
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicoLegadoClient() : 
                base(ServicoLegadoClient.GetDefaultBinding(), ServicoLegadoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicoLegado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoLegadoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoLegadoClient.GetBindingForEndpoint(endpointConfiguration), ServicoLegadoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoLegadoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoLegadoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoLegadoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoLegadoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoLegadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OrderIntake.Infrastructure.Legado.Gerado.ValidarEReservarPedidoResponse> ValidarEReservarPedidoAsync(OrderIntake.Infrastructure.Legado.Gerado.ValidarEReservarPedidoRequest request)
        {
            return base.Channel.ValidarEReservarPedidoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicoLegado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicoLegado))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5297/ServicoLegado.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicoLegadoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicoLegado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicoLegadoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicoLegado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicoLegado,
        }
    }
}
